import argparse
import csv
import hashlib
import re
from pathlib import Path
from typing import Optional, Tuple


LABEL_FROM_DIR = {
    "python": "Python",
    "java": "Java",
    "c": "C",
    "cplusplus": "C++",
    "cplusplusplus": "C++",
    "csharp": "C#",
    "javascript": "JavaScript",
    "typescript": "TypeScript",
    "html": "HTML",
    "css": "CSS",
    "xml": "XML",
    "svg": "SVG",
    "json": "JSON",
    "yaml": "YAML",
    "toml": "TOML",
    "ini": "INI",
    "csv": "CSV",
    "sql": "SQL",
    "markdown": "Markdown",
    "shell": "Shell",
    "dockerfile": "Dockerfile",
    "makefile": "Makefile",
    "php": "PHP",
    "ruby": "Ruby",
    "go": "Go",
    "rust": "Rust",
    "kotlin": "Kotlin",
    "swift": "Swift",
    "r": "R",
    "lua": "Lua",
    "perl": "Perl",
    "scala": "Scala",
    "latex": "LaTeX",
}


def read_text_file(path: Path) -> Optional[str]:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n").replace("\r", "\n")


def remove_non_printable_noise(text: str) -> str:
    """
    Keep normal whitespace, remove suspicious control characters.
    """
    return "".join(
        ch for ch in text
        if ch == "\n" or ch == "\t" or ord(ch) >= 32
    )


def truncate_text(text: str, max_lines: int = 120, max_chars: int = 20_000) -> str:
    lines = text.split("\n")
    lines = lines[:max_lines]
    text = "\n".join(lines)
    return text[:max_chars].strip()


def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="ignore")).hexdigest()


def is_probably_binary(text: str) -> bool:
    if "\x00" in text:
        return True

    if len(text) == 0:
        return False

    control_chars = sum(
        1 for ch in text
        if ord(ch) < 32 and ch not in "\n\r\t"
    )
    return control_chars / len(text) > 0.02


def is_probably_base64_blob(text: str) -> bool:
    compact = re.sub(r"\s+", "", text)

    if len(compact) < 500:
        return False

    base64_chars = sum(
        1 for ch in compact
        if ch.isalnum() or ch in "+/="
    )

    return base64_chars / len(compact) > 0.95


def is_probably_minified(text: str) -> bool:
    lines = text.splitlines()
    if not lines:
        return False

    avg_line_length = sum(len(line) for line in lines) / len(lines)
    max_line_length = max(len(line) for line in lines)

    # Common minified bundle symptom.
    if max_line_length > 5_000:
        return True

    if avg_line_length > 500:
        return True

    return False


def is_probably_auto_generated(text: str) -> bool:
    head = text[:2_000].lower()

    patterns = [
        "auto-generated",
        "autogenerated",
        "automatically generated",
        "generated by",
        "do not edit",
        "this file was generated",
        "<auto-generated",
    ]

    return any(pattern in head for pattern in patterns)


def basic_mislabel_check(label: str, text: str) -> Tuple[bool, str]:
    """
    Conservative checks only.
    Do not reject aggressively, because many real files are mixed.
    """
    stripped = text.strip()
    lower = stripped.lower()

    if label == "JSON":
        if not (
            (stripped.startswith("{") and stripped.endswith("}"))
            or (stripped.startswith("[") and stripped.endswith("]"))
        ):
            return False, "json_not_object_or_array"

    if label == "XML":
        if "<" not in stripped or ">" not in stripped:
            return False, "xml_without_tags"

    if label == "SVG":
        if "<svg" not in lower:
            return False, "svg_without_svg_tag"

    if label == "HTML":
        has_html_signal = (
            "<!doctype html" in lower
            or "<html" in lower
            or "<body" in lower
            or "<head" in lower
        )
        if not has_html_signal:
            return False, "html_without_html_signal"

    if label == "CSV":
        lines = [line for line in stripped.splitlines() if line.strip()]
        if len(lines) >= 3:
            comma_lines = sum(1 for line in lines[:10] if "," in line)
            semicolon_lines = sum(1 for line in lines[:10] if ";" in line)
            tab_lines = sum(1 for line in lines[:10] if "\t" in line)
            if max(comma_lines, semicolon_lines, tab_lines) < 2:
                return False, "csv_without_delimiter_pattern"

    return True, "ok"


def validate_sample(label: str, text: Optional[str]) -> Tuple[bool, str]:
    if text is None:
        return False, "read_error"

    if len(text.strip()) < 10:
        return False, "too_short"

    if is_probably_binary(text):
        return False, "binary_like"

    if is_probably_base64_blob(text):
        return False, "base64_blob"

    if is_probably_minified(text):
        return False, "minified_or_huge_line"

    if is_probably_auto_generated(text):
        return False, "auto_generated"

    ok, reason = basic_mislabel_check(label, text)
    if not ok:
        return False, reason

    return True, "ok"


def collect_raw_files(raw_dir: Path):
    for class_dir in sorted(raw_dir.iterdir()):
        if not class_dir.is_dir():
            continue

        dir_name = class_dir.name
        label = LABEL_FROM_DIR.get(dir_name, dir_name)

        for path in sorted(class_dir.iterdir()):
            if path.is_file():
                yield label, path


def clean_dataset(raw_dir: Path, output_dir: Path, metadata_path: Path):
    cleaned_root = output_dir / "cleaned_files"
    cleaned_root.mkdir(parents=True, exist_ok=True)

    seen_hashes = set()
    rows = []

    total = 0
    valid = 0
    invalid = 0
    duplicate = 0

    for label, raw_path in collect_raw_files(raw_dir):
        total += 1

        raw_text = read_text_file(raw_path)
        is_valid, reason = validate_sample(label, raw_text)

        cleaned_path = ""
        num_chars = 0
        num_lines = 0
        avg_line_length = 0.0
        max_line_length = 0

        if is_valid:
            text = normalize_newlines(raw_text)
            text = remove_non_printable_noise(text)
            text = truncate_text(text)

            h = content_hash(text)
            if h in seen_hashes:
                is_valid = False
                reason = "duplicate"
                duplicate += 1
            else:
                seen_hashes.add(h)

                label_dir = cleaned_root / safe_dir_name(label)
                label_dir.mkdir(parents=True, exist_ok=True)

                file_id = f"{safe_dir_name(label)}_{valid:06d}"
                cleaned_file = label_dir / f"{file_id}.txt"
                cleaned_file.write_text(text, encoding="utf-8")

                cleaned_path = str(cleaned_file)
                num_chars = len(text)
                lines = text.splitlines()
                num_lines = len(lines)
                avg_line_length = (
                    sum(len(line) for line in lines) / num_lines
                    if num_lines > 0 else 0.0
                )
                max_line_length = max((len(line) for line in lines), default=0)

                valid += 1

        if not is_valid:
            invalid += 1
            file_id = f"{safe_dir_name(label)}_invalid_{invalid:06d}"
        else:
            file_id = Path(cleaned_path).stem

        rows.append({
            "file_id": file_id,
            "label": label,
            "raw_path": str(raw_path),
            "cleaned_path": cleaned_path,
            "num_chars": num_chars,
            "num_lines": num_lines,
            "avg_line_length": round(avg_line_length, 4),
            "max_line_length": max_line_length,
            "is_valid": is_valid,
            "reason": reason,
        })

    metadata_path.parent.mkdir(parents=True, exist_ok=True)

    with metadata_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "file_id",
                "label",
                "raw_path",
                "cleaned_path",
                "num_chars",
                "num_lines",
                "avg_line_length",
                "max_line_length",
                "is_valid",
                "reason",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    print("========== CLEANING SUMMARY ==========")
    print(f"Raw dir: {raw_dir}")
    print(f"Cleaned dir: {cleaned_root}")
    print(f"Metadata: {metadata_path}")
    print(f"Total files scanned: {total}")
    print(f"Valid files: {valid}")
    print(f"Invalid files: {invalid}")
    print(f"Duplicates removed: {duplicate}")


def safe_dir_name(label: str) -> str:
    return (
        label.lower()
        .replace("#", "sharp")
        .replace("+", "plus")
        .replace(" ", "_")
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw-dir", default="data/raw")
    parser.add_argument("--output-dir", default="data/processed")
    parser.add_argument("--metadata-path", default="data/processed/metadata.csv")
    args = parser.parse_args()

    raw_dir = Path(args.raw_dir)
    output_dir = Path(args.output_dir)
    metadata_path = Path(args.metadata_path)

    if not raw_dir.exists():
        raise FileNotFoundError(f"Raw data directory not found: {raw_dir}")

    clean_dataset(
        raw_dir=raw_dir,
        output_dir=output_dir,
        metadata_path=metadata_path,
    )


if __name__ == "__main__":
    main()